#! /bin/bash

# check sudo
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: Please run as root user."
    exit 1
fi

echo "[*] Updating ..."
cd /tmp
git clone https://github.com/manesec/maketoolkit.git maketoolkit
cd maketoolkit
chmod u+x *.sh
./reinstall.sh
cd /tmp
rm -rf /tmp/maketoolkit